### ISSUE TITLE
Can i add some new index on config file

### ISSUE THREAD

**Issue by Davronjuraev** [emadha/laravel-dynamic-config#1]
In my case wanna add new index with values, can i do this with this package?

**Comment by emadha** [comment]
you can set any config file to be dynamic (store/read from database) as long as you put 'dynamic'=>true to it.

Can you explain more?

**Comment by Davronjuraev** [comment]
> you can set any config file to be dynamic (store/read from database) as long as you put 'dynamic'=>true to it.
> 
> Can you explain more?
